### ISSUE TITLE
Add a PR Template

### ISSUE THREAD

**Issue by aashutoshrathi** [iiitv/getmein-web#21] opened 2018-10-01 05:59 UTC
Add PR template to help reviewers to know which issue is referenced and what changes are done with a demo.

**Comment by DipanshKhandelwal** [comment] 2018-10-01 06:00
Assign this to me @aashutoshrathi

**Comment by Ananthavijay** [comment] 2018-10-01 06:09
can I work on this?

**Comment by aashutoshrathi** [comment] 2018-10-01 06:18
Go on @Ananthavijay

**Comment by Ananthavijay** [comment] 2018-10-01 06:20
thanks

**Comment by ABHISHEK-G0YAL** [comment] 2018-10-01 07:36
done

**Comment by Ananthavijay** [comment] 2018-10-01 09:16
@ABHISHEK-G0YAL Pls see the issue is assigned to me.

**Closed** 2018-10-01 15:17 UTC
Labels: Hacktoberfest
